### ISSUE TITLE
CANT LOGIN IN IT 

### ISSUE THREAD

**Issue by icesuncc** [ecency/hivesigner-ui#47]
i try login in and keep said  active or memo etc . but i already register and set to sell my cards with user name icesuncc  then next day  now i cant login in to check card or pick up $$$ hivesigner keep reject me so what heck going on 

Invalid username or password. You need to use master, active, posting or memo key to login.

**Comment by feruzm** [comment]
@icesuncc did it work now?

**Comment by icesuncc** [comment]
yes it work thanks
@feruzm
