### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by shakavon** [ecency/hivesigner-ui#59]
Hi I was able to get into my account yesterday before I wiped my cache and cookies but now I am unable to I haven't changed anything and going directly from the download file I got from HiveSigner with my username and 4 other passwords

**Comment by feruzm** [comment]
@shakavon could you share link what from what page you came and what was the url? Hivesigner doesn’t have download file section.

**Comment by shakavon** [comment]
https://hivesigner.com/import?redirect=accounts

when I opened the hive signer account it gave a packet

--------------- YOUR ACCOUNT -------------
Username:
Password:

------------------------ PRIVATE KEYS ----------------------
Owner:
Active:
Posting:
Memo:

-------------------------- KEY DESCRIPTION -----------------------
Owner:   Change Password, Change Keys, Recover Account
Active:  Transfer Funds, Power up/down, Voting Witnesses/Proposals
Posting: Post, Comment, Vote, Reblog, Follow, Profile
Memo:    Send/View encrypted messages on transfers

---------------------- WHERE TO USE YOUR KEYS --------------------
Hive Keychain and Hive Signer should allow you to do transactions
on all Hive sites and applications.

PeakD.com allows your own browser to store Posting key via
"PeakLock" login method (an alternative for mobile).

Be very careful directly using your keys on any other website or
application.

**Comment by feruzm** [comment]
That is likely from hiveonboard account creation service, you can login into hivesigner.com with your username and active key from that same download.

**Comment by shakavon** [comment]
yeah no luck idk is it majorly important that I have access to this I can still log into all the other services

**Comment by feruzm** [comment]
@shakavon what's your username and what private key did you try for login? Which website/services did you try? Ecency.com didn't work? Trying to understand in what part of service there is issue.

**Comment by feruzm** [comment]
Any screenshot of error, you can share? Please try your private active key on hivesigner and see if it helps.

**Comment by feruzm** [comment]
@shakavon could you please check again, if problem persist, more details would help if you still having issues.

**Comment by AndreNavarro1234** [comment]
Hola cómo hago para cambiar mi clave que se me olvidó?

**Comment by AndreNavarro1234** [comment]
De Hivesigner

**Comment by eapo** [comment]
> Any screenshot of error, you can share? Please try your private active key on hivesigner and see if it helps.

i have the screen recording about the same problem: https://pixeldrain.com/u/6kXSNJX9
