### ISSUE TITLE
Error message: RPCError: Missing Active Authority

### ISSUE THREAD

**Issue by q123joe** [ecency/hivesigner-ui#74]
hi! I just wanna bidding in peakmonsters ,but it always says :

Your transaction was not successfully broadcasted
Error message: RPCError: Missing Active Authority baganono auth={"weight_threshold":1,"account_auths":[],"key_auths":[["STM6Rgd8cbRQUXapUSorZNysEEzqdFwt8rw1fGRUwvVkxUuTe8hpK",1]]} owner={"weight_threshold":1,"account_auths":[],"key_auths":[["STM73Ro9N6q7Vg99nHvkWeAQFgA2wfS4X7z8uXjj7Y4CzvMj2SVqG",1]]}

what should I do now?

**Comment by feruzm** [comment]
Hi
You sure you have logged in (imported) account with active key? If not sure, check hivesigner.com/auths page and see if you have active private key imported already.
