### ISSUE TITLE
Error message: RPCError: trx.expiration=2022-07-15T18:53:03 now=2022-07-15T16:51:09 max_til_exp=3600

### ISSUE THREAD

**Issue by WS191** [ecency/hivesigner-ui#78]
I am getting the following error when trying to rent splinterlands cards from Peakmonsters:  Error message: RPCError: trx.expiration=2022-07-15T18:53:03 now=2022-07-15T16:51:09 max_til_exp=3600

I removed and reactivated Hivesigner but it did not resolve the error.

**Comment by feruzm** [comment]
It says expiration was expected to be 1 hour but peakmonsters or you are setting it to be 2 hours. Could that be the case? @WS191

**Comment by WS191** [comment]
I don't think so, I never set a time manually

**Comment by feruzm** [comment]
Have you asked if peakmonsters team did some changes? Otherwise one of the rpc nodes have issue which we need to check which one and replace that. 🧐

**Comment by WS191** [comment]
I posted on their discord and recommendation was to use the Keychain. My
other accounts work fine today with hivesigner.

**Comment by feruzm** [comment]
Ok, so there was no respond if they made some changes or not then?! We will see, what we can find out from our side. Thank you!

**Comment by WS191** [comment]
Right, thank you for checking it!
