### ISSUE TITLE
Callback for sign endpoint

### ISSUE THREAD

**Issue by reichert-splinterlands** [ecency/hivesigner-ui#80]
When broadcasting an operation via `hivesigner.com/sign` there is currently afaik no way to get the result. I.e. in case I broadcast a custom_json, I would like to receive the transactionId, which is shown on the screen, but not accessible by the frontend that created the sign url.

A solution could be to have use the `callbackURL` defined in the client used by the login function for signs as well. Sign functions could also have a flag whether callback should be used or not.

Update: There is already the parameter `redirect_uri ` but after redirected, the transaction id isn't added as written here: 

```
The result will be : https://ecency.com/?id=XXX
```

**Comment by feruzm** [comment]
for reference:
`redirect_uri` should be in this format for hivesigner to be able to fill data properly and return to your redirect destination.

`...&redirect=https://ecency.com/?tid={{id}}&block={{block}}&txn={{txn}}&signature={{sig}}`
