### ISSUE TITLE
Hivesigner Error on Blocktrades

### ISSUE THREAD

**Issue by eftnow** [ecency/hivesigner-ui#87]
When I try to authorise a transaction on Blocktrades I get this error. I am on Ubuntu 22.4

Error message: RPCError: Missing Active Authority eftnow auth={"weight_threshold":1,"account_auths":[],"key_auths":[["STM7ZNm7RFK16RoPrN8aAoUqm2jm9bXpKu4iKCyfDdGe2DQPwZoRa",1]]} owner={"weight_threshold":1,"account_auths":[],"key_auths":[["STM6t2LNawpRas6RfQuUjHTZVNV8GYQqpnaBmwLWn4bBJGcNayPMF",1]]}

![Screenshot from 2023-03-07 09-10-54](https://user-images.githubusercontent.com/127188325/223362610-4c5c0675-0afc-4a08-ac81-ac29bbf8851f.png)

**Comment by feruzm** [comment]
@eftnow this usually means hivesigner doesn’t have your active private key. You login/import your account with private posting key? Go to hivesigner.com/auths and make sure your active private key is present. If present hivesigner should show you reveal key button, you can import individual key on that page too.

**Comment by eftnow** [comment]
The Active private key is present.

**Comment by eftnow** [comment]
I saw that it wasn't there yesterday, so I added it. It is now correct.

**Comment by feruzm** [comment]
@eftnow even after adding you are getting this error?

**Comment by eftnow** [comment]
I haven't added the Owner key, but I'm not sure I would need to for this. I understand it isn't a good idea to add this anywhere.

**Comment by feruzm** [comment]
> Where do I find the transaction format?

Before you sign transaction, hivesigner shows you screen/form where you can see transaction details, please take screenshot of that.

**Comment by eftnow** [comment]
Hi any news on this? Or is there a way I can go in and reset everything on Hivesigner?

**Comment by feruzm** [comment]
> Hi any news on this? Or is there a way I can go in and reset everything on Hivesigner?

You can go to https://hivesigner.com/accounts and select effected account, click on `Remove from Hivesigner` button and after that you can reimport account again to hivesigner and perform operation again from Blocktrades.

**Comment by eftnow** [comment]
Thank you I'll give that a go.

**Comment by feruzm** [comment]
@eftnow if this is working or resolved, let me know

**Comment by eftnow** [comment]
I resolved it by clearing and reinstating the account.Sent from my iPhoneOn 26 Jun 2023, at 08:34, Feruz M ***@***.***> wrote:﻿
@eftnow if this is working or resolved, let me know

**Comment by feruzm** [comment]
@eftnow great, thank you! I will close this ticket then!
